version: '3'

volumes:
  static:
  database:

services:
  janmeery:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: janmeery
    container_name: janmeery
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: janmeery_nginx
    container_name: janmeery_nginx
    volumes:
      - static:/apps/janmeery/static
    ports:
      - "80:80"
      - "443:443"